words = [
    "gopls",
    "keymap",
    "keymaps",
    "metamethods",
    "metatable",
    "mkdir",
    "neotest",
    "newindex",
    "nodoc",
    "nvim",
    "reparsing",
    "sourcer",
    "spm",
    "tbl",
]
