#!/bin/sh

export XDG_CONFIG_HOME='test/xdg/config/'
export XDG_STATE_HOME='test/xdg/local/state/'
export XDG_DATA_HOME='test/xdg/local/share/'

plugin_dir="${XDG_DATA_HOME}nvim/site/pack/testing/start"

echo "Linking plugin to ${plugin_dir}"
mkdir -p "${plugin_dir}"

ln -s "$(pwd)" "${plugin_dir}/spm.nvim"
nvim --cmd 'set loadplugins' -l $@
exit_code=$?
rm "${plugin_dir}/spm.nvim"

exit $exit_code
