name: Tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly]
        lua-version: ["5.1"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Verify submodules
        run: git submodule status

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ matrix.lua-version }}

      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@v5

      - name: Setup dependencies
        run: |
          luarocks install luacov
          luarocks install busted

      - name: Run tests
        run: |
          make unit-test
          make automated-test
